{% set name = "zope.sqlalchemy" %}
{% set version = "3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zope.sqlalchemy-{{ version }}.tar.gz
  sha256: d9c2c3be695c213c5e22b7f7c6a4a214fa8eb5940b033465ba1c10a9d8b346db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - packaging
    - setuptools
    - sqlalchemy >=1.1,!=1.4.0,!=1.4.1,!=1.4.2,!=1.4.3,!=1.4.4,!=1.4.5,!=1.4.6
    - transaction >=1.6.0
    - zope.interface >=3.6.0

test:
  imports:
    - zope
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/zopefoundation/zope.sqlalchemy
  summary: Minimal Zope/SQLAlchemy transaction integration
  license: ZPL-2.1 AND BSD-3-Clause
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
